name: flutter_bingmaps
description: Porting Microsoft Bing Maps to Flutter  
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
